import {
    FiTrendingUp,
    FiVideo,
    FiLayout,
    FiPenTool,
    FiBarChart2,
    FiGlobe,
    FiYoutube,
    FiInstagram,
    FiTwitter,
    FiShield,
    FiCode,
    FiMail,
    FiShoppingBag,
    FiImage,
    FiEdit3,
    FiActivity,
    FiMessageSquare,
    FiCpu,
    FiDatabase,
    FiBookOpen,
    FiZap,
    FiMic,
    FiSearch,
    FiCamera,
    FiFeather,
    FiLayers,
} from "react-icons/fi";
import { FaFacebookF, FaTiktok, FaLinkedinIn, FaRobot, FaBrain } from "react-icons/fa6";

export const serviceCategories = [
    {
        title: "Core Infrastructure & Engineering",
        icon: FiLayout,
        slug: "infrastructure",
        color: "from-emerald-500 to-teal-400",
        description: "Enterprise-grade systems architecture, cloud migrations, and server management.",
        services: [
            { name: "Cloud Migration & Architecture", icon: FiGlobe },
            { name: "Enterprise Server Maintenance", icon: FiDatabase },
            { name: "System Administration (Linux/Win)", icon: FiShield },
            { name: "Custom Software Development", icon: FiCode },
            { name: "Network Security & Optimization", icon: FiZap },
            { name: "API & App Integration", icon: FiCpu },
        ],
    },
    {
        title: "AI Automation & Modernization",
        icon: FaBrain,
        slug: "ai-modernization",
        color: "from-violet-500 to-fuchsia-400",
        description: "Modernize legacy workflows with cutting-edge AI ecosystems and automation.",
        services: [
            { name: "Custom AI Chatbot Ecosystems", icon: FaRobot },
            { name: "Business Workflow Automation", icon: FiZap },
            { name: "Internal Knowledge Custom GPTs", icon: FiBookOpen },
            { name: "AI-Powered Process Optimization", icon: FiCpu },
            { name: "Legacy System Modernization", icon: FiActivity },
        ],
    },
    {
        title: "AI Content & Multi-Platform",
        icon: FiEdit3,
        slug: "ai-content",
        color: "from-rose-500 to-orange-400",
        description: "Scale your reach with AI-driven content generation across every digital platform.",
        services: [
            { name: "AI Video & Voice Generation", icon: FiMic },
            { name: "YouTube & Platform Management", icon: FiYoutube },
            { name: "Data-Driven Social Strategy", icon: FiTrendingUp },
            { name: "AI-Enhanced SEO & Copywriting", icon: FiSearch },
            { name: "Growth Analytics & Reporting", icon: FiBarChart2 },
        ],
    },
    {
        title: "Creative & Branding",
        icon: FiPenTool,
        slug: "creative-branding",
        color: "from-orange-500 to-amber-400",
        description: "Build a memorable brand with stunning visuals and compelling corporate stories.",
        services: [
            { name: "Logo & Visual Identity", icon: FiEdit3 },
            { name: "Brand Strategy & Positioning", icon: FiTrendingUp },
            { name: "Marketing Collateral", icon: FiLayers },
            { name: "Photography & Art Direction", icon: FiCamera },
            { name: "Corporate Storytelling", icon: FiFeather },
        ],
    },
];
